USE [master]
GO

IF DB_ID (N'ClinicaGAP') IS NOT NULL
DROP DATABASE ClinicaGAP
GO

CREATE DATABASE ClinicaGAP
GO

USE [ClinicaGAP]
GO

SET XACT_ABORT ON

BEGIN TRAN [TranE]

	CREATE TABLE ESTADO(
		ID_ESTADO int identity(1,1) NOT NULL,
		DESCRIPCION varchar(20) NOT NULL,
		CONSTRAINT PK_ESTADO PRIMARY KEY (ID_ESTADO)
	)

	CREATE TABLE TIPO_CITA(
		ID_TIPO_CITA int identity(1,1) NOT NULL,
		DESCRIPCION varchar(30) NOT NULL,
		ESTADO int NOT NULL,
		CONSTRAINT PK_TIPO_CITA PRIMARY KEY (ID_TIPO_CITA),
		CONSTRAINT FK_TIPO_CITA_ESTADO FOREIGN KEY (ESTADO) REFERENCES ESTADO(ID_ESTADO),
	)
	
	CREATE TABLE PACIENTE(
		ID_PACIENTE int identity(1,1) NOT NULL,
		CEDULA varchar(15) NOT NULL,
		PRIMER_NOMBRE varchar(60) NOT NULL,
		SEGUNDO_NOMBRE varchar(60) NULL,
		PRIMER_APELLIDO varchar(60) NOT NULL,
		SEGUNDO_APELLIDO varchar(60) NOT NULL,
		TELEFONO_CONTACTO varchar(15) NULL,
		CORREO_CONTACTO varchar(100) NULL,
		CONSTRAINT PK_PACIENTE PRIMARY KEY (ID_PACIENTE)
	)

	CREATE TABLE CITA(
		ID_CITA int IDENTITY(1,1),
		FECHA_CITA datetime NOT NULL,
		TIPO_CITA int NOT NULL,
		DESCRIPCION varchar(150) NOT NULL,
		ESTADO int NOT NULL,
		ID_PACIENTE int NOT NULL,
		CONSTRAINT PK_CITA PRIMARY KEY (ID_CITA),
		CONSTRAINT FK_CITA_TIPO_CITA FOREIGN KEY (TIPO_CITA) REFERENCES TIPO_CITA(ID_TIPO_CITA),
		CONSTRAINT FK_CITA_ESTADO FOREIGN KEY (ESTADO) REFERENCES ESTADO(ID_ESTADO),
		CONSTRAINT FK_CITA_ID_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE)
	)
	
	/*INSERCIONES ESTADO*/
	INSERT INTO ESTADO VALUES('Activa')
	INSERT INTO ESTADO VALUES('Cancelada')
	INSERT INTO ESTADO VALUES('Finalizada')

	/*INSERCIONES TIPO_CITA*/
	INSERT INTO TIPO_CITA VALUES('Medicina general',1)
	INSERT INTO TIPO_CITA VALUES('Odontologia',1)
	INSERT INTO TIPO_CITA VALUES('Pediatria',1)
	INSERT INTO TIPO_CITA VALUES('Neurologia',1)

	/*INSERCIONES PACIENTE*/
	INSERT INTO PACIENTE VALUES('604110387','Cristhian','Mariano','Hernandez','Hernandez','+50689733663','cristhianhh21@gmail.com')
	INSERT INTO PACIENTE VALUES('604240358','Janice','Paola','Montenegro','Baltodano','+50689738607','jpmb_14@hotmail.com')
	INSERT INTO PACIENTE VALUES('602340002','Marjorie',null,'Hernandez','Rojas','+573207684011',null)
	
	/*INSERCIONES CITA*/
	INSERT INTO CITA VALUES('2020-01-06 19:10:00.000',1,'El cliente indica que viene a control general',1,1)
	INSERT INTO CITA VALUES('2020-01-03 08:00:00.000',2,'La cliente desea realizarse un blanqueamiento dental',1,2)
	INSERT INTO CITA VALUES('2020-01-06 10:00:00.000',2,'La cliente desea realizarse una limpieza dental',1,3)
	
	/*OBTENCIONES*/
	SELECT * FROM ESTADO
	SELECT * FROM TIPO_CITA
	SELECT * FROM PACIENTE
	SELECT * FROM CITA
	
COMMIT TRAN [TranE]
GO