//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaGAP.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class CITA
    {
        public int ID_CITA { get; set; }
        [Required(ErrorMessage = "La fecha de la cita es requerida.")]
        public System.DateTime FECHA_CITA { get; set; }
        public int TIPO_CITA { get; set; }
        [Required(ErrorMessage = "La descripción es requerida.")]
        [StringLength(150, MinimumLength = 1, ErrorMessage = "La descripción no debe superar los 150 caracteres.")]
        public string DESCRIPCION { get; set; }
        public int ESTADO { get; set; }
        public int ID_PACIENTE { get; set; }
    
        public virtual ESTADO ESTADO1 { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual TIPO_CITA TIPO_CITA1 { get; set; }
    }
}